# Generated by Django 5.0.3 on 2024-04-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceitem',
            options={'ordering': ['-date'], 'verbose_name': 'Price Item', 'verbose_name_plural': 'Price Items'},
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
