# Generated by Django 5.0.3 on 2024-04-03 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_priceitem_options_alter_priceitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
